services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dynastydb
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
