FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /App
COPY . ./
RUN dotnet publish DataPipeline/DataPipeline.csproj -o /App/out

FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /App

COPY --from=build /App/out .

USER app

ENTRYPOINT [ "dotnet", "DataPipeline.dll" ]