FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:81f6d622fe21ed9d31375167f62a3538ff4d6835f9d5e6da9c2defa8a84b7687 AS build
WORKDIR /App
COPY . ./
RUN dotnet publish ClientApi/ClientApi.csproj -o /App/out

FROM mcr.microsoft.com/dotnet/aspnet:9.0@sha256:3dcb33395722d14c80d19107158293ed677b2c07841100d51df07275ae2b2682
WORKDIR /App
COPY --from=build /App/out .
ENTRYPOINT [ "dotnet", "ClientApi.dll" ]