// <auto-generated />
using System;
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Consts;

#nullable disable

namespace Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "data_source", new[] { "dynasty_process", "fantasy_calc", "keep_trade_cut", "mfl", "sleeper" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "included_pos", new[] { "qb", "rb", "te", "wr" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "team", new[] { "ari", "atl", "bal", "buf", "car", "chi", "cin", "cle", "dal", "den", "det", "gb", "hou", "ind", "jax", "kc", "lac", "lar", "lv", "mia", "min", "ne", "no", "null_team", "nyg", "nyj", "phi", "pit", "sea", "sf", "tb", "ten", "was" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Db.Models.ExternalIdModel", b =>
                {
                    b.Property<DataSource>("DataSource")
                        .HasColumnType("data_source")
                        .HasColumnName("data_source");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("DataSource", "SourceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("external_id_player_lookup");
                });

            modelBuilder.Entity("Db.Models.PlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.PrimitiveCollection<IncludedPosition[]>("Positions")
                        .IsRequired()
                        .HasColumnType("included_pos[]")
                        .HasColumnName("positions");

                    b.Property<TeamAbbr>("Team")
                        .HasColumnType("team")
                        .HasColumnName("team");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("Db.Models.PlayerValueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DataSource>("DataSource")
                        .HasColumnType("data_source")
                        .HasColumnName("data_source");

                    b.Property<bool>("IsSuperFlex")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_flex");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_values");
                });

            modelBuilder.Entity("Db.Models.ExternalIdModel", b =>
                {
                    b.HasOne("Db.Models.PlayerModel", "Player")
                        .WithMany("ExternalIds")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Db.Models.PlayerValueModel", b =>
                {
                    b.HasOne("Db.Models.PlayerModel", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Db.Models.PlayerModel", b =>
                {
                    b.Navigation("ExternalIds");
                });
#pragma warning restore 612, 618
        }
    }
}
