// <auto-generated />
using System;
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "data_source", new[] { "keep_trade_cut", "fantasy_calc", "sleeper", "dynasty_process", "reddit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "included_position", new[] { "qb", "wr", "rb", "te" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "team_abbr", new[] { "buf", "mia", "ne", "nyj", "dal", "nyg", "phi", "was", "bal", "cin", "cle", "pit", "chi", "det", "gb", "min", "hou", "ind", "jax", "ten", "atl", "car", "no", "tb", "den", "kc", "lv", "lac", "ari", "lar", "sf", "sea", "null_team" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Db.Models.ExternalIdPlayerLookup", b =>
                {
                    b.Property<int>("DataSource")
                        .HasColumnType("integer")
                        .HasColumnName("data_source");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("DataSource", "SourceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("external_id_player_lookup");
                });

            modelBuilder.Entity("Db.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.PrimitiveCollection<int[]>("Positions")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("positions");

                    b.Property<int>("Team")
                        .HasColumnType("integer")
                        .HasColumnName("team");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("Db.Models.PlayerValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DataSource")
                        .HasColumnType("integer")
                        .HasColumnName("data_source");

                    b.Property<bool>("IsSuperFlex")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_flex");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_values");
                });

            modelBuilder.Entity("Db.Models.ExternalIdPlayerLookup", b =>
                {
                    b.HasOne("Db.Models.Player", "Player")
                        .WithMany("ExternalIds")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Db.Models.PlayerValue", b =>
                {
                    b.HasOne("Db.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Db.Models.Player", b =>
                {
                    b.Navigation("ExternalIds");
                });
#pragma warning restore 612, 618
        }
    }
}
